In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("two_stage_opamp_results.csv")
df.head()

,W1,L1,W3,L3,W5,L5,W6,L6,W7,L7,IB,CC,Gain,Gain_Phase,UGBW,PM_db,PM_PH
0,16.104u,352.295n,18.930u,187.153n,17.793u,208.824n,62.784u,257.507n,143.962u,404.029n,16.796u,1.169p,81.252534,96.915994,116187.893923,38.755184,0.0
1,17.836u,400.167n,19.356u,365.170n,14.664u,393.713n,219.334u,203.530n,14.279u,372.222n,18.621u,0.942p,67.094592,91.836707,22646.713367,39.052338,0.0
2,6.369u,228.236n,16.987u,290.500n,20.086u,512.121n,308.204u,200.738n,137.441u,495.181n,22.642u,2.210p,74.316378,90.560692,51985.585215,39.039567,0.0
3,14.502u,460.147n,20.400u,194.920n,6.506u,186.525n,69.183u,261.415n,119.229u,253.501n,14.198u,0.753p,76.888961,115.954525,77719.352735,38.959244,0.0
4,7.153u,260.007n,10.058u,304.949n,19.990u,329.225n,316.483u,200.802n,123.995u,312.287n,27.326u,1.820p,70.014279,91.728164,31690.472228,39.065607,0.0

In [3]:
para = ["W1","L1","W3","L3","W5","L5","W6","L6","W7","L7","IB","CC"]

In [4]:
df_new = df[para]
df_new.head()

,W1,L1,W3,L3,W5,L5,W6,L6,W7,L7,IB,CC
0,16.104u,352.295n,18.930u,187.153n,17.793u,208.824n,62.784u,257.507n,143.962u,404.029n,16.796u,1.169p
1,17.836u,400.167n,19.356u,365.170n,14.664u,393.713n,219.334u,203.530n,14.279u,372.222n,18.621u,0.942p
2,6.369u,228.236n,16.987u,290.500n,20.086u,512.121n,308.204u,200.738n,137.441u,495.181n,22.642u,2.210p
3,14.502u,460.147n,20.400u,194.920n,6.506u,186.525n,69.183u,261.415n,119.229u,253.501n,14.198u,0.753p
4,7.153u,260.007n,10.058u,304.949n,19.990u,329.225n,316.483u,200.802n,123.995u,312.287n,27.326u,1.820p

In [5]:
df_new.to_csv("parameters.csv", index=False)